spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Add or update this specific block
  session:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always

server:
  servlet:
    context-path: /demo
