spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-init-sql: "SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED"
      data-source-properties:
        prepareThreshold: 0

  # Add or update this specific block
  session:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always

server:
  servlet:
    context-path: /demo
