spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres

  # Add or update this specific block
  session:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always

server:
  servlet:
    context-path: /demo
